# name: Build and Analyze with SonarQube

# on: push

# jobs:
#   build-and-analyze:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         project:
#           - group_1_SOLID_GRASP
#           - group_2_SOLID_GRASP
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up JDK 17
#       uses: actions/setup-java@v2
#       with:
#         distribution: 'temurin'
#         java-version: 17

#     - name: Run SonarQube Scan for ${{ matrix.project }}
#       uses: sonarsource/sonarqube-scan-action@master
#       with:
#         projectBaseDir: ${{ matrix.project }}
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

name: Build and Analyze with SonarQube

on: push

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - group_1_SOLID_GRASP
          - group_2_SOLID_GRASP
          - group_3_SOLID_GRASP
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Run SonarQube Scan for ${{ matrix.project }}
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: ${{ matrix.project }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
